export const GETNOTE_REQUEST = 'GETNOTE_REQUEST'
export const GETNOTE_SUCCESS = 'GETNOTE_SUCCESS'
export const GETNOTE_ERROR = 'GETNOTE_ERROR'

export const CREATENOTE_REQUEST = 'CREATENOTE_REQUEST'
export const CREATENOTE_SUCCESS = 'CREATENOTE_SUCCESS'
export const CREATENOTE_ERROR = 'CREATENOTE_ERROR'

export const UPDATENOTE_REQUEST = 'UPDATENOTE_REQUEST'
export const UPDATENOTE_SUCCESS = 'UPDATENOTE_SUCCESS'
export const UPDATENOTE_ERROR = 'UPDATENOTE_ERROR'

export const DELETENOTE_REQUEST = 'DELETENOTE_REQUEST'
export const DELETENOTE_SUCCESS = 'DELETENOTE_SUCCESS'
export const DELETENOTE_ERROR = 'DELETENOTE_ERROR'

