export const GETNOTE_REQUEST = 'GETNOTE_REQUEST'
export const GETNOTE_SUCCESS = 'GETNOTE_SUCCESS'
export const GETNOTE_ERROR = 'GETNOTE_ERROR'

export const CREATENOTE_REQUEST = 'CREATENOTE_REQUEST'
export const CREATENOTE_SUCCESS = 'CREATENOTE_SUCCESS'
export const CREATENOTE_ERROR = 'CREATENOTE_ERROR'

